.\" Manpage for SIC Relocation Loader
.\" Contact teamloader@123mail.org
.TH man 1 "07 December 2021" "1.0" "SIC Relocation Loader Man Page"
.SH NAME
SIC Relocation Loader 
.SH DESCRIPTION
This program is a relocating loader for the SIC machiene. The relocating loader will accept 3 command-line arguments and will output the T and E records with their relocations completed.
.SH OPTIONS
.IP -f
interpret PAGE argument as filename or file 
.IP -s
interpret PAGE argument as start address in hex
.IP -p
interpret PAGE argument as platform type - SIC or SICXE
.SH AUTHOR 
Team PassA
.SH CREDITS
.PP
This man page is created for demonstration purposes only. 

